### ISSUE TITLE
lin_pow formula

### ISSUE THREAD

**Issue by fguilhaumon** [txm676/sars#34]
In lin_pow, we have the following summary output :
`data(galap)
fit <- lin_pow(galap, con = 1)
summary(fit)
#> Model = Log-log power
#> 
#> Call:
#> lm(formula = S ~ A, data = log.data)
#> 
...`

I would prefer to have a formula with log(variables):
`lm(formula = log(S) ~ log(A), data = data)`

Would be ok to not transform the data or not use the transformed data.

**Comment by txm676** [comment]
Done, but had to be within an if statement, as if 0 richness values present it has to be log(S + x)
